# Generated by Django 4.1.3 on 2022-11-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_deposit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
