# Generated by Django 4.1.3 on 2022-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_deposit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
