# Generated by Django 4.1.3 on 2022-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_deposit_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='misc_case_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
