# Generated by Django 4.1.3 on 2022-11-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_deposit_misc_case_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statutorydeposit',
            old_name='mact_name',
            new_name='mac_case_details',
        ),
        migrations.RemoveField(
            model_name='statutorydeposit',
            name='mac_case_no',
        ),
        migrations.AlterField(
            model_name='statutorydeposit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statutorydeposit',
            name='order_date',
            field=models.CharField(max_length=100),
        ),
    ]
