# Generated by Django 3.1.7 on 2021-03-18 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210316_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemovement',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 18, 16, 12, 31, 483521)),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='section_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_section_from', to='app.section'),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 18, 16, 12, 31, 483521)),
        ),
    ]
