# Generated by Django 4.1.3 on 2022-11-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_filemovement_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('order_date', models.DateField()),
                ('misc_case_no', models.CharField(max_length=500)),
                ('main_case_no', models.CharField(max_length=500)),
                ('appellant', models.CharField(max_length=500)),
                ('party_name', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('in_words', models.CharField(max_length=500)),
                ('cheque_no', models.IntegerField(max_length=10)),
                ('cheque_date', models.DateField()),
                ('bank_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryDeposit',
            fields=[
                ('id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('order_date', models.DateField()),
                ('mact_name', models.CharField(max_length=800)),
                ('mac_case_no', models.CharField(max_length=500)),
                ('party_name', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('in_words', models.CharField(max_length=500)),
                ('cheque_no', models.IntegerField(max_length=10)),
                ('cheque_date', models.DateField()),
                ('bank_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='filemovement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filemovement',
            name='puc',
        ),
        migrations.RemoveField(
            model_name='filemovement',
            name='put_up_by',
        ),
        migrations.RemoveField(
            model_name='filemovement',
            name='section_from',
        ),
        migrations.RemoveField(
            model_name='filemovement',
            name='section_to',
        ),
        migrations.RemoveField(
            model_name='puc',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='puc',
            name='file',
        ),
        migrations.RemoveField(
            model_name='puc',
            name='section',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='section',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='FileMovement',
        ),
        migrations.DeleteModel(
            name='PUC',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='statutorydeposit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
