# Generated by Django 4.1.3 on 2022-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_deposit_statutorydeposit_remove_filemovement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='cheque_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='cheque_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='order_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statutorydeposit',
            name='cheque_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statutorydeposit',
            name='cheque_no',
            field=models.CharField(max_length=100),
        ),
    ]
